apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-svc
  name: nginx-svc
  namespace: default
spec:
  type: NodePort
  selector:
    app: webserver
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
