apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-3
  namespace: default
  labels:
    app: resource
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    ports:
      - containerPort: 80
        protocol: TCP
    resources:
      requests:
        memory: "100Mi"
        cpu: "100m"
      limits:
        memory: "150Mi"
        cpu: "300m"