apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-2
  namespace: default
  labels:
    app: webserver
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    volumeMounts: 
    - name: password-volume
      mountPath: /usr/share/nginx/html
  volumes:
  - name: password-volume
    configMap:
      name: password
      items:
      - key: password
        path: index.html
  restartPolicy: Never