apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-1
  namespace: default
  labels:
    app: webserver
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    ports:
      - containerPort: 80
        protocol: TCP
    volumeMounts: 
    - name: account-volume
      mountPath: /usr/share/nginx/html
  volumes:
  - name: account-volume
    secret:
      secretName: account
      items:
      - key: username
        path: index.html
